### ISSUE TITLE
store user details

### ISSUE THREAD

**Issue by matthewberryman** [AcrossTheCloud/TBA21-API#11]
Store email (as login username) of person submitting a person / item entry.
Ref https://aws-amplify.github.io/amplify-js/media/authentication_guide#retrieve-current-authenticated-user

**Comment by mehrdadgit** [comment]
I believe this is already being tracked in Jira too happy to close off @matthewberryman ?

**Comment by matthewberryman** [comment]
Yes tracked in Jira
